# Generated by Django 6.0.7 on 2026-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('is_examinable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Kuddus er original syllabus statement')),
                ('filtered_topics', models.TextField(blank=True, help_text='AI diye clean kora bullet list')),
                ('study_plan_json', models.TextField(blank=True, help_text='Structured JSON study plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
