# Generated by Django 6.0.7 on 2026-07-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.TextField(help_text='The actual, verbatim school rule')),
                ('category', models.CharField(blank=True, help_text='e.g. Captain Duties, Homework, Discipline', max_length=100)),
            ],
        ),
    ]
