# Generated by Django 6.0.7 on 2026-07-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tiffin', 'Tiffin Theft'), ('bribe', 'Bribes'), ('syllabus', 'Syllabus Bloat'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified_strike', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RollNumberHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_roll', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
