# Generated by Django 6.0.7 on 2026-07-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('cash', 'Cash Extortion (Washroom Toll)'), ('food', 'Stolen Food/Tiffin')], max_length=10)),
                ('amount_taka', models.PositiveIntegerField(default=0, help_text='Taka amount (cash type er jonno)')),
                ('food_item', models.CharField(blank=True, help_text='Food item naam (food type er jonno)', max_length=100)),
                ('estimated_calories', models.PositiveIntegerField(default=0, help_text='Food item er calorie estimate')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
