# Generated by Django 6.0.7 on 2026-07-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_taka',
            field=models.PositiveIntegerField(default=0, help_text='Taka amount (for cash type)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='estimated_calories',
            field=models.PositiveIntegerField(default=0, help_text='Estimated calories of the food item'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='food_item',
            field=models.CharField(blank=True, help_text='Food item name (for food type)', max_length=100),
        ),
    ]
