# Generated by Django 6.0.7 on 2026-07-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('library', 'Library'), ('playground', 'Playground'), ('corridor', 'Corridor'), ('classroom', 'Classroom'), ('canteen', 'Canteen')], max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False, help_text='Captain marks true once handled')),
                ('synced_from_offline', models.BooleanField(default=False, help_text='True if this was queued offline and synced later')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
