# Generated by Django 6.0.7 on 2026-07-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Section B', max_length=50)),
                ('rows', models.PositiveIntegerField(default=6)),
                ('columns', models.PositiveIntegerField(default=5)),
                ('aisle_after_column', models.PositiveIntegerField(default=0, help_text='Center aisle kon column er por - 0 hole aisle nai')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=20, unique=True)),
                ('height_cm', models.PositiveIntegerField()),
                ('needs_front_row', models.BooleanField(default=False, help_text='Vision/hearing impairment thakle True koro - height niye bepar na kore front e boshbe')),
            ],
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='seating.classroomlayout')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seating.student')),
            ],
            options={
                'unique_together': {('layout', 'row', 'column')},
            },
        ),
    ]
